{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.9.aar",
          "url": "flutter_profile-1.9.9.aar",
          "size": 11174010,
          "sha512": "951972cd98b85bd75cc8d92843f01926b5cfe538d518a61d7e6cb651ae83494ec88c84f9ec1150dec2f75f3e3480a18e3d8f6fba8854638c35df9417462fd839",
          "sha256": "b898cbfdc8be98aba6ccc65011b3f06a79a43fec02cace96e2d1a079d3c9907e",
          "sha1": "2060d756130ddeb5532b8d6ec1432df77930cf94",
          "md5": "87e5014e7bf69b926bf7f00b2b5e64bb"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.9.aar",
          "url": "flutter_profile-1.9.9.aar",
          "size": 11174010,
          "sha512": "951972cd98b85bd75cc8d92843f01926b5cfe538d518a61d7e6cb651ae83494ec88c84f9ec1150dec2f75f3e3480a18e3d8f6fba8854638c35df9417462fd839",
          "sha256": "b898cbfdc8be98aba6ccc65011b3f06a79a43fec02cace96e2d1a079d3c9907e",
          "sha1": "2060d756130ddeb5532b8d6ec1432df77930cf94",
          "md5": "87e5014e7bf69b926bf7f00b2b5e64bb"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.9.9-sources.jar",
          "url": "flutter_profile-1.9.9-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.9.9-javadoc.jar",
          "url": "flutter_profile-1.9.9-javadoc.jar",
          "size": 261621,
          "sha512": "6429c30ed6d9ce6cb44507b4336c819e180a0e484a2ca33ad774397e267bbd5b246de0ccf9226e01c087841b5a9576cc6e0352ec32284df9e2b440b955f128c5",
          "sha256": "44b0c10d2d882e18e733ab1b2200ccdfe3a4421a41004c81c3ff92b187374b6e",
          "sha1": "e0a6e3b4aeac9f1691404ac4f8b61d134386aed4",
          "md5": "e4aac148b751cb1f8e6bcfa9307f0080"
        }
      ]
    }
  ]
}
