{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
<<<<<<<< HEAD:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.8/flutter_profile-1.9.8.module
    "version": "1.9.8",
========
    "version": "1.9.9",
>>>>>>>> develop:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.9/flutter_profile-1.9.9.module
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
<<<<<<<< HEAD:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.8/flutter_profile-1.9.8.module
          "name": "flutter_profile-1.9.8.aar",
          "url": "flutter_profile-1.9.8.aar",
          "size": 11173105,
          "sha512": "5893d56538a056123b7d3f99e17fd788ed02c257212bcdf861c9ec34caa73c4c7a12a05eef64ba450ec90cc7275475d143bf04d03947cfc2e595e89165e9c27d",
          "sha256": "05e7fc1f9a6eadd07e46574adc65556eb1bed26a242aa601f7049bc225c8c61e",
          "sha1": "50aabbed8c187f75621ffb0488983780e8b7f482",
          "md5": "51467ab899a32be501bcf5f268d0acd9"
========
          "name": "flutter_profile-1.9.9.aar",
          "url": "flutter_profile-1.9.9.aar",
          "size": 11174010,
          "sha512": "951972cd98b85bd75cc8d92843f01926b5cfe538d518a61d7e6cb651ae83494ec88c84f9ec1150dec2f75f3e3480a18e3d8f6fba8854638c35df9417462fd839",
          "sha256": "b898cbfdc8be98aba6ccc65011b3f06a79a43fec02cace96e2d1a079d3c9907e",
          "sha1": "2060d756130ddeb5532b8d6ec1432df77930cf94",
          "md5": "87e5014e7bf69b926bf7f00b2b5e64bb"
>>>>>>>> develop:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.9/flutter_profile-1.9.9.module
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
<<<<<<<< HEAD:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.8/flutter_profile-1.9.8.module
          "name": "flutter_profile-1.9.8.aar",
          "url": "flutter_profile-1.9.8.aar",
          "size": 11173105,
          "sha512": "5893d56538a056123b7d3f99e17fd788ed02c257212bcdf861c9ec34caa73c4c7a12a05eef64ba450ec90cc7275475d143bf04d03947cfc2e595e89165e9c27d",
          "sha256": "05e7fc1f9a6eadd07e46574adc65556eb1bed26a242aa601f7049bc225c8c61e",
          "sha1": "50aabbed8c187f75621ffb0488983780e8b7f482",
          "md5": "51467ab899a32be501bcf5f268d0acd9"
========
          "name": "flutter_profile-1.9.9.aar",
          "url": "flutter_profile-1.9.9.aar",
          "size": 11174010,
          "sha512": "951972cd98b85bd75cc8d92843f01926b5cfe538d518a61d7e6cb651ae83494ec88c84f9ec1150dec2f75f3e3480a18e3d8f6fba8854638c35df9417462fd839",
          "sha256": "b898cbfdc8be98aba6ccc65011b3f06a79a43fec02cace96e2d1a079d3c9907e",
          "sha1": "2060d756130ddeb5532b8d6ec1432df77930cf94",
          "md5": "87e5014e7bf69b926bf7f00b2b5e64bb"
>>>>>>>> develop:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.9/flutter_profile-1.9.9.module
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
<<<<<<<< HEAD:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.8/flutter_profile-1.9.8.module
          "name": "flutter_profile-1.9.8-sources.jar",
          "url": "flutter_profile-1.9.8-sources.jar",
========
          "name": "flutter_profile-1.9.9-sources.jar",
          "url": "flutter_profile-1.9.9-sources.jar",
>>>>>>>> develop:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.9/flutter_profile-1.9.9.module
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
<<<<<<<< HEAD:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.8/flutter_profile-1.9.8.module
          "name": "flutter_profile-1.9.8-javadoc.jar",
          "url": "flutter_profile-1.9.8-javadoc.jar",
          "size": 261621,
          "sha512": "218f433f2b1dc1dc9d043349b9fa9c0fa2b4542891c9e6c34d927857e4d0a92fb778898cdd340f6a89bbdc5fd08897bf5bfa68178fedd98bebec4222e2a52887",
          "sha256": "a124df2da66d99df5d230bb04ede6fdea8c95229b033e910c99481490bc66ec9",
          "sha1": "758fde798004a902a40d8de503e1e35045056b72",
          "md5": "e28527eaf67923a056af48440c24d851"
========
          "name": "flutter_profile-1.9.9-javadoc.jar",
          "url": "flutter_profile-1.9.9-javadoc.jar",
          "size": 261621,
          "sha512": "6429c30ed6d9ce6cb44507b4336c819e180a0e484a2ca33ad774397e267bbd5b246de0ccf9226e01c087841b5a9576cc6e0352ec32284df9e2b440b955f128c5",
          "sha256": "44b0c10d2d882e18e733ab1b2200ccdfe3a4421a41004c81c3ff92b187374b6e",
          "sha1": "e0a6e3b4aeac9f1691404ac4f8b61d134386aed4",
          "md5": "e4aac148b751cb1f8e6bcfa9307f0080"
>>>>>>>> develop:sdk-nss-engine/host/outputs/repo/com/gigya/gigyaNativeScreensetsEngine/flutter_profile/1.9.9/flutter_profile-1.9.9.module
        }
      ]
    }
  ]
}
