{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.8.aar",
          "url": "flutter_profile-1.9.8.aar",
          "size": 11173105,
          "sha512": "5893d56538a056123b7d3f99e17fd788ed02c257212bcdf861c9ec34caa73c4c7a12a05eef64ba450ec90cc7275475d143bf04d03947cfc2e595e89165e9c27d",
          "sha256": "05e7fc1f9a6eadd07e46574adc65556eb1bed26a242aa601f7049bc225c8c61e",
          "sha1": "50aabbed8c187f75621ffb0488983780e8b7f482",
          "md5": "51467ab899a32be501bcf5f268d0acd9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.8.aar",
          "url": "flutter_profile-1.9.8.aar",
          "size": 11173105,
          "sha512": "5893d56538a056123b7d3f99e17fd788ed02c257212bcdf861c9ec34caa73c4c7a12a05eef64ba450ec90cc7275475d143bf04d03947cfc2e595e89165e9c27d",
          "sha256": "05e7fc1f9a6eadd07e46574adc65556eb1bed26a242aa601f7049bc225c8c61e",
          "sha1": "50aabbed8c187f75621ffb0488983780e8b7f482",
          "md5": "51467ab899a32be501bcf5f268d0acd9"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.9.8-sources.jar",
          "url": "flutter_profile-1.9.8-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.9.8-javadoc.jar",
          "url": "flutter_profile-1.9.8-javadoc.jar",
          "size": 261621,
          "sha512": "218f433f2b1dc1dc9d043349b9fa9c0fa2b4542891c9e6c34d927857e4d0a92fb778898cdd340f6a89bbdc5fd08897bf5bfa68178fedd98bebec4222e2a52887",
          "sha256": "a124df2da66d99df5d230bb04ede6fdea8c95229b033e910c99481490bc66ec9",
          "sha1": "758fde798004a902a40d8de503e1e35045056b72",
          "md5": "e28527eaf67923a056af48440c24d851"
        }
      ]
    }
  ]
}
