{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_release",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.0.aar",
          "url": "flutter_release-1.8.0.aar",
          "size": 7638291,
          "sha512": "6c9f724f701c5ea428cf34c62de39312516cef0637c75590fcb940739adb37498eaf7d6ccbdbfe7162296f38128257a15ad7c88aa7efddd878c318d1c5dd763f",
          "sha256": "a1e9e4937ae7af42808e61aedbd939450dac10aa99d0cc811b944b310185f8af",
          "sha1": "e5209039827723365a24df1b39eef0a549dab93c",
          "md5": "7dcff9956ebe30805b39095e46b518df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.0.aar",
          "url": "flutter_release-1.8.0.aar",
          "size": 7638291,
          "sha512": "6c9f724f701c5ea428cf34c62de39312516cef0637c75590fcb940739adb37498eaf7d6ccbdbfe7162296f38128257a15ad7c88aa7efddd878c318d1c5dd763f",
          "sha256": "a1e9e4937ae7af42808e61aedbd939450dac10aa99d0cc811b944b310185f8af",
          "sha1": "e5209039827723365a24df1b39eef0a549dab93c",
          "md5": "7dcff9956ebe30805b39095e46b518df"
        }
      ]
    }
  ]
}
