{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_debug",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.9.2.aar",
          "url": "flutter_debug-1.9.2.aar",
          "size": 13773097,
          "sha512": "7c824837143c744f2cac26f55b95c98b0023e8cfa74216125761ef33a9bf6a04c241389194b2630db2e5375157db4eabdbd9324a17643169537599e0ca8fa5e7",
          "sha256": "feb9ae85619cb547a2ae198a296f4203e5209a2423f5bcd8f5e59bf1a7708930",
          "sha1": "3e9296b1ce5d70e2d1e6ba64930c3b10bff09492",
          "md5": "39ea78d2b6c29e5837911397fb204b11"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.9.2.aar",
          "url": "flutter_debug-1.9.2.aar",
          "size": 13773097,
          "sha512": "7c824837143c744f2cac26f55b95c98b0023e8cfa74216125761ef33a9bf6a04c241389194b2630db2e5375157db4eabdbd9324a17643169537599e0ca8fa5e7",
          "sha256": "feb9ae85619cb547a2ae198a296f4203e5209a2423f5bcd8f5e59bf1a7708930",
          "sha1": "3e9296b1ce5d70e2d1e6ba64930c3b10bff09492",
          "md5": "39ea78d2b6c29e5837911397fb204b11"
        }
      ]
    }
  ]
}
