{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.6.0.aar",
          "url": "flutter_profile-1.6.0.aar",
          "size": 350466,
          "sha512": "be695c79eed87b3fba43fd6a37cc84ea43449a0265fc976cf3ee446a90ac2fe5ba25f92b4944375f1c2a7184f56574369902bbbae16a4b0d36e925997031478b",
          "sha256": "d8e3903bc91bc6736dfd267c81dd26e8436704d6f5dbc3f9034949b796b91679",
          "sha1": "d861aa256eca77f7651347aac9420f8e460f6344",
          "md5": "a82b32137bf8ae85779e350177e33ba5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.6.0.aar",
          "url": "flutter_profile-1.6.0.aar",
          "size": 350466,
          "sha512": "be695c79eed87b3fba43fd6a37cc84ea43449a0265fc976cf3ee446a90ac2fe5ba25f92b4944375f1c2a7184f56574369902bbbae16a4b0d36e925997031478b",
          "sha256": "d8e3903bc91bc6736dfd267c81dd26e8436704d6f5dbc3f9034949b796b91679",
          "sha1": "d861aa256eca77f7651347aac9420f8e460f6344",
          "md5": "a82b32137bf8ae85779e350177e33ba5"
        }
      ]
    }
  ]
}
