{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.6.0.aar",
          "url": "flutter_profile-1.6.0.aar",
          "size": 341893,
          "sha512": "030bdd87e7acda48cbc67e18e7c55a37edc96bd263bcb61ee474f7e51faaa135731bfdb7b5a657687dbba426b5752e6977143c735d5037a35eab9cd849c53887",
          "sha256": "f73dacc56e5b369ae2f5950f929811d440ebd1a263bcd3305a09e47800082f93",
          "sha1": "87c90b8218a03176f2c5d18e806012971e2c5946",
          "md5": "448dedafebf7a505182433fb5ab78dcd"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.6.0.aar",
          "url": "flutter_profile-1.6.0.aar",
          "size": 341893,
          "sha512": "030bdd87e7acda48cbc67e18e7c55a37edc96bd263bcb61ee474f7e51faaa135731bfdb7b5a657687dbba426b5752e6977143c735d5037a35eab9cd849c53887",
          "sha256": "f73dacc56e5b369ae2f5950f929811d440ebd1a263bcd3305a09e47800082f93",
          "sha1": "87c90b8218a03176f2c5d18e806012971e2c5946",
          "md5": "448dedafebf7a505182433fb5ab78dcd"
        }
      ]
    }
  ]
}
