{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_release",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.7.1.aar",
          "url": "flutter_release-1.7.1.aar",
          "size": 7360216,
          "sha512": "1c1f5aef0cc05aac94afe56149a60ccb7ebef1117fa278cd5c7de2164861535b30c86d915bc57417eb793091d7fa1c312d3ad242168b6b5f2c7d8980bb41933d",
          "sha256": "b3aa2ff7d0470f4a408c6296fdfd8da7de7e606beb96bc98fa5e33a43e483ac2",
          "sha1": "749f80e126c0ec9dd582f32687d9f92fbf6d2cd7",
          "md5": "cc55f509ed5f57757cd03440dfba6809"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.7.1.aar",
          "url": "flutter_release-1.7.1.aar",
          "size": 7360216,
          "sha512": "1c1f5aef0cc05aac94afe56149a60ccb7ebef1117fa278cd5c7de2164861535b30c86d915bc57417eb793091d7fa1c312d3ad242168b6b5f2c7d8980bb41933d",
          "sha256": "b3aa2ff7d0470f4a408c6296fdfd8da7de7e606beb96bc98fa5e33a43e483ac2",
          "sha1": "749f80e126c0ec9dd582f32687d9f92fbf6d2cd7",
          "md5": "cc55f509ed5f57757cd03440dfba6809"
        }
      ]
    }
  ]
}
