{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.8.2.aar",
          "url": "flutter_profile-1.8.2.aar",
          "size": 10934537,
          "sha512": "ce6b254c041e77789d74aef7f1caceeacc17f4d3c80df9205a1b0a9787279035fc78eb9daa1869e230ddbd56a44c8b9f5039882248a8829fa4e8e9cd2091a754",
          "sha256": "f5f3e8cecb2d7995aaa0039d9039a044e6c28d00fe09d5f3dbae43c70ed649d5",
          "sha1": "4efdfc3ef957f677512313bb39fcf875008a0037",
          "md5": "59543ebc82e4fc199bbb4067a6c45f6c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.8.2.aar",
          "url": "flutter_profile-1.8.2.aar",
          "size": 10934537,
          "sha512": "ce6b254c041e77789d74aef7f1caceeacc17f4d3c80df9205a1b0a9787279035fc78eb9daa1869e230ddbd56a44c8b9f5039882248a8829fa4e8e9cd2091a754",
          "sha256": "f5f3e8cecb2d7995aaa0039d9039a044e6c28d00fe09d5f3dbae43c70ed649d5",
          "sha1": "4efdfc3ef957f677512313bb39fcf875008a0037",
          "md5": "59543ebc82e4fc199bbb4067a6c45f6c"
        }
      ]
    }
  ]
}
