{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.7.1.aar",
          "url": "flutter_profile-1.7.1.aar",
          "size": 10506090,
          "sha512": "e29dfa881183f2639028fa3a0e78138d342b729e525a0b9fa8dc85769b1a997ac48a095e94f5e0bff3eec3c721aba351d7eebab0f2d84d79bd7190dae72676e0",
          "sha256": "5d04a72c04d5c3b111d431209ed509d9215cc5c3217da3ce2d8a83a04b309ff2",
          "sha1": "0ff0e827576149822a82c2292a47e84a3a276a87",
          "md5": "284b2de48d33a02af79e930d2cf42de2"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.7.1.aar",
          "url": "flutter_profile-1.7.1.aar",
          "size": 10506090,
          "sha512": "e29dfa881183f2639028fa3a0e78138d342b729e525a0b9fa8dc85769b1a997ac48a095e94f5e0bff3eec3c721aba351d7eebab0f2d84d79bd7190dae72676e0",
          "sha256": "5d04a72c04d5c3b111d431209ed509d9215cc5c3217da3ce2d8a83a04b309ff2",
          "sha1": "0ff0e827576149822a82c2292a47e84a3a276a87",
          "md5": "284b2de48d33a02af79e930d2cf42de2"
        }
      ]
    }
  ]
}
