{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.8.0.aar",
          "url": "flutter_profile-1.8.0.aar",
          "size": 10946683,
          "sha512": "a1127bc14576e902ffe94b8cbab09e18160854acbd332a48b2d391113887c0c2b6c25b1e55bfe4fa0693824a7f9612bcf75439505874eb5be31d203b7957f35c",
          "sha256": "808887ab1f35108786d8bb38995d9461d85e9599b305f081de0ee07a3e3d2ff5",
          "sha1": "05b19617c0d1da0e05c01df39564a3ca9676a676",
          "md5": "2883a6e2139d58fd9312f1b646dc72f7"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.8.0.aar",
          "url": "flutter_profile-1.8.0.aar",
          "size": 10946683,
          "sha512": "a1127bc14576e902ffe94b8cbab09e18160854acbd332a48b2d391113887c0c2b6c25b1e55bfe4fa0693824a7f9612bcf75439505874eb5be31d203b7957f35c",
          "sha256": "808887ab1f35108786d8bb38995d9461d85e9599b305f081de0ee07a3e3d2ff5",
          "sha1": "05b19617c0d1da0e05c01df39564a3ca9676a676",
          "md5": "2883a6e2139d58fd9312f1b646dc72f7"
        }
      ]
    }
  ]
}
