{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.2.aar",
          "url": "flutter_profile-1.9.2.aar",
          "size": 10760076,
          "sha512": "d23c0ce8d48331bdae31abc63b569135d54dd5533bd2a4b132dac190e79f682906646fd7d1882705a0b9b5ea3ecb4d2a559adddc2a98da33158521929630f8e9",
          "sha256": "b29fbd7a1f649d8d07c6b379a618188f7348143d9812b5dd6308f3324c01bec3",
          "sha1": "226ac04bef380c908871e9c45e47e25ed1010dfc",
          "md5": "8d112948b8efbfec243471bb4b53ad1c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.2.aar",
          "url": "flutter_profile-1.9.2.aar",
          "size": 10760076,
          "sha512": "d23c0ce8d48331bdae31abc63b569135d54dd5533bd2a4b132dac190e79f682906646fd7d1882705a0b9b5ea3ecb4d2a559adddc2a98da33158521929630f8e9",
          "sha256": "b29fbd7a1f649d8d07c6b379a618188f7348143d9812b5dd6308f3324c01bec3",
          "sha1": "226ac04bef380c908871e9c45e47e25ed1010dfc",
          "md5": "8d112948b8efbfec243471bb4b53ad1c"
        }
      ]
    }
  ]
}
