{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.1.aar",
          "url": "flutter_profile-1.9.1.aar",
          "size": 10730503,
          "sha512": "d5312d380ea340e00f1cd1723b7013e4542a9c5f4dd80d51d828f576763bcaf7661955373cee6c61b16797684118b2697aada8afc106dbaffcc7b06e1471c678",
          "sha256": "99d0df532cc777725f397a663ac0982419d8cc5ba1199b14ed7271bf2f7835cf",
          "sha1": "33b91385eeb1e325e148ee2e96df1c9376ca5209",
          "md5": "4f8c211c77b7f8023b06313b469d51a8"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.1.aar",
          "url": "flutter_profile-1.9.1.aar",
          "size": 10730503,
          "sha512": "d5312d380ea340e00f1cd1723b7013e4542a9c5f4dd80d51d828f576763bcaf7661955373cee6c61b16797684118b2697aada8afc106dbaffcc7b06e1471c678",
          "sha256": "99d0df532cc777725f397a663ac0982419d8cc5ba1199b14ed7271bf2f7835cf",
          "sha1": "33b91385eeb1e325e148ee2e96df1c9376ca5209",
          "md5": "4f8c211c77b7f8023b06313b469d51a8"
        }
      ]
    }
  ]
}
