{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_release",
    "version": "1.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f73bfc4522dd0bc87bbcdb4bb3088082755c5e87"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f73bfc4522dd0bc87bbcdb4bb3088082755c5e87"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f73bfc4522dd0bc87bbcdb4bb3088082755c5e87"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f73bfc4522dd0bc87bbcdb4bb3088082755c5e87"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.7.aar",
          "url": "flutter_release-1.9.7.aar",
          "size": 7678753,
          "sha512": "7ce1c897599539b255759f3999d7d92a961fdfb225b449ed7fdd26b25f764c7f20f7015f477c6b20eccfd49367ea5d79e4b768b32e0e66d853ee534544a091d1",
          "sha256": "d403ff5ce0ddef98f47c91d279337137e74ee258ce77b942ca143dd94cfd1d38",
          "sha1": "96a3befcdce20c2a14cc04f4b3f33a421bb38cf6",
          "md5": "d6d6a4fcf3eb3bc2c75a31aa44725f76"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f73bfc4522dd0bc87bbcdb4bb3088082755c5e87"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f73bfc4522dd0bc87bbcdb4bb3088082755c5e87"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f73bfc4522dd0bc87bbcdb4bb3088082755c5e87"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f73bfc4522dd0bc87bbcdb4bb3088082755c5e87"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.7.aar",
          "url": "flutter_release-1.9.7.aar",
          "size": 7678753,
          "sha512": "7ce1c897599539b255759f3999d7d92a961fdfb225b449ed7fdd26b25f764c7f20f7015f477c6b20eccfd49367ea5d79e4b768b32e0e66d853ee534544a091d1",
          "sha256": "d403ff5ce0ddef98f47c91d279337137e74ee258ce77b942ca143dd94cfd1d38",
          "sha1": "96a3befcdce20c2a14cc04f4b3f33a421bb38cf6",
          "md5": "d6d6a4fcf3eb3bc2c75a31aa44725f76"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.9.7-sources.jar",
          "url": "flutter_release-1.9.7-sources.jar",
          "size": 1008,
          "sha512": "6ac6436640930885931051b8fac4aa27f8a847d33e9b96f7e4d8f422aec9ff627670e26ba860e90a5c8c34771ade8d2e0b6a9090b2e46e13082465d6b00ecf72",
          "sha256": "0b75aba57699df30f0bac04dfcc4d000c9b1c96130d09e2346e753cb8f55518e",
          "sha1": "75379ad607250ff70d501d22dd660929347193d5",
          "md5": "a730f69ca4df125c3b9d3a5416b60d6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.9.7-javadoc.jar",
          "url": "flutter_release-1.9.7-javadoc.jar",
          "size": 261621,
          "sha512": "401966b1feb4523962103476dde1c606dc09975fb39a2498efcca96d44fc4a7fcf48f59bec2f6cc50f9b918b92b36a2a274d8fad960b916f57f3e7ab0f1f3086",
          "sha256": "1769ae10692e15c5ddbbad46e341c5fb84d7bf049e65ccae5d4e9b3b484139d1",
          "sha1": "381deebdaa866fc4ff330c657607439c75edd76a",
          "md5": "2434da870b1eba55309b09da4fe34ba8"
        }
      ]
    }
  ]
}
