{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_release",
    "version": "1.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.1.aar",
          "url": "flutter_release-1.9.1.aar",
          "size": 7513460,
          "sha512": "c08e4f045a12ab7909ad65f6d6c70c03420d916c90561329bc344794f0b6349886e18474490d2a9af934a0cd0e2823c133daed62f799e0c3bde282c837ae3b99",
          "sha256": "80822a34c745875c79dbbbd13d2eaf2ddf475d852b236fca32d269de4375ea7c",
          "sha1": "7bef30c4b3961cd58871b51d13a5e4007f7cabae",
          "md5": "0aff48ea1dbc46f5c46adc3b4d74da7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.1.aar",
          "url": "flutter_release-1.9.1.aar",
          "size": 7513460,
          "sha512": "c08e4f045a12ab7909ad65f6d6c70c03420d916c90561329bc344794f0b6349886e18474490d2a9af934a0cd0e2823c133daed62f799e0c3bde282c837ae3b99",
          "sha256": "80822a34c745875c79dbbbd13d2eaf2ddf475d852b236fca32d269de4375ea7c",
          "sha1": "7bef30c4b3961cd58871b51d13a5e4007f7cabae",
          "md5": "0aff48ea1dbc46f5c46adc3b4d74da7b"
        }
      ]
    }
  ]
}
