{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-debug.aar",
          "url": "flutter-1.6.0-debug.aar",
          "size": 12177249,
          "sha512": "1d8d24b16487a436f761661f0503911e3a16a121862697d4da40a88e71f3459becb770eec6e110b8fee7828cf24fa9086de3452a8164c9adc0746e96e01f7d26",
          "sha256": "eaa0e8e68bc41e6d999334b899f44d68d98adb63d1bebb63703b13b1d2b7b432",
          "sha1": "b4aa0bc08290f7361c50cc7316498cada7a233d9",
          "md5": "1b13b13bbc8c84f44b595927f033b6ee"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-debug.aar",
          "url": "flutter-1.6.0-debug.aar",
          "size": 12177249,
          "sha512": "1d8d24b16487a436f761661f0503911e3a16a121862697d4da40a88e71f3459becb770eec6e110b8fee7828cf24fa9086de3452a8164c9adc0746e96e01f7d26",
          "sha256": "eaa0e8e68bc41e6d999334b899f44d68d98adb63d1bebb63703b13b1d2b7b432",
          "sha1": "b4aa0bc08290f7361c50cc7316498cada7a233d9",
          "md5": "1b13b13bbc8c84f44b595927f033b6ee"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-release.aar",
          "url": "flutter-1.6.0-release.aar",
          "size": 6799606,
          "sha512": "6f2a6e28548e65a19b9cda51b483bb780f33bcf3ed8b940c7d3f2b9cc2858764ae6d7b2191a5a1dc6864dfd3044bba2032115b77bec637dc9141fe52eced1cfd",
          "sha256": "f0d46f8941eb1c093a7ba203bb5dc3fff1306a0ef39008a6628f32434d7efcf5",
          "sha1": "7816aa7466e2a9e8b06e3763a2c5d5b8a447b9ca",
          "md5": "e5253668f2960951441a9193f6330f1a"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-release.aar",
          "url": "flutter-1.6.0-release.aar",
          "size": 6799606,
          "sha512": "6f2a6e28548e65a19b9cda51b483bb780f33bcf3ed8b940c7d3f2b9cc2858764ae6d7b2191a5a1dc6864dfd3044bba2032115b77bec637dc9141fe52eced1cfd",
          "sha256": "f0d46f8941eb1c093a7ba203bb5dc3fff1306a0ef39008a6628f32434d7efcf5",
          "sha1": "7816aa7466e2a9e8b06e3763a2c5d5b8a447b9ca",
          "md5": "e5253668f2960951441a9193f6330f1a"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-profile.aar",
          "url": "flutter-1.6.0-profile.aar",
          "size": 341893,
          "sha512": "030bdd87e7acda48cbc67e18e7c55a37edc96bd263bcb61ee474f7e51faaa135731bfdb7b5a657687dbba426b5752e6977143c735d5037a35eab9cd849c53887",
          "sha256": "f73dacc56e5b369ae2f5950f929811d440ebd1a263bcd3305a09e47800082f93",
          "sha1": "87c90b8218a03176f2c5d18e806012971e2c5946",
          "md5": "448dedafebf7a505182433fb5ab78dcd"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-profile.aar",
          "url": "flutter-1.6.0-profile.aar",
          "size": 341893,
          "sha512": "030bdd87e7acda48cbc67e18e7c55a37edc96bd263bcb61ee474f7e51faaa135731bfdb7b5a657687dbba426b5752e6977143c735d5037a35eab9cd849c53887",
          "sha256": "f73dacc56e5b369ae2f5950f929811d440ebd1a263bcd3305a09e47800082f93",
          "sha1": "87c90b8218a03176f2c5d18e806012971e2c5946",
          "md5": "448dedafebf7a505182433fb5ab78dcd"
        }
      ]
    }
  ]
}
