{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-debug.aar",
          "url": "flutter-1.6.0-debug.aar",
          "size": 12179302,
          "sha512": "e759d4571dbf24f7d9abf3482d90ddc53f9c4da6527b0415cc0025e56d963290b8db45fec1bafbaa4e44994bbc6b86ffe5ad2b37e62496fc97a0e29340bf0acc",
          "sha256": "bda87d94b00b7c366b7b425e81af4082e25a2844d185c94fe80e5074d25f53e4",
          "sha1": "71b93f755e21bd64eb1fd55556bfa527e27acfbc",
          "md5": "768a918fc6d74e62fb8ffd4fc8417c57"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-debug.aar",
          "url": "flutter-1.6.0-debug.aar",
          "size": 12179302,
          "sha512": "e759d4571dbf24f7d9abf3482d90ddc53f9c4da6527b0415cc0025e56d963290b8db45fec1bafbaa4e44994bbc6b86ffe5ad2b37e62496fc97a0e29340bf0acc",
          "sha256": "bda87d94b00b7c366b7b425e81af4082e25a2844d185c94fe80e5074d25f53e4",
          "sha1": "71b93f755e21bd64eb1fd55556bfa527e27acfbc",
          "md5": "768a918fc6d74e62fb8ffd4fc8417c57"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-release.aar",
          "url": "flutter-1.6.0-release.aar",
          "size": 6798372,
          "sha512": "332b2d1a02e9c4270839e776b24712eb964aa3b38f8536f1865471f163561dbf26527729b0e0d0579b5f255b5913c8f2afadec669a4729c4df7b2697e5e2b622",
          "sha256": "eb6b5ea4e2278735a7f2fb94f757a35a08146cb6e6602df1496b4ac639b47403",
          "sha1": "b8553d77d62a74b900547398d5a18c6fb5f3a953",
          "md5": "081bf8045abaf1f1c4a10c507c74e969"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-release.aar",
          "url": "flutter-1.6.0-release.aar",
          "size": 6798372,
          "sha512": "332b2d1a02e9c4270839e776b24712eb964aa3b38f8536f1865471f163561dbf26527729b0e0d0579b5f255b5913c8f2afadec669a4729c4df7b2697e5e2b622",
          "sha256": "eb6b5ea4e2278735a7f2fb94f757a35a08146cb6e6602df1496b4ac639b47403",
          "sha1": "b8553d77d62a74b900547398d5a18c6fb5f3a953",
          "md5": "081bf8045abaf1f1c4a10c507c74e969"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-profile.aar",
          "url": "flutter-1.6.0-profile.aar",
          "size": 350466,
          "sha512": "be695c79eed87b3fba43fd6a37cc84ea43449a0265fc976cf3ee446a90ac2fe5ba25f92b4944375f1c2a7184f56574369902bbbae16a4b0d36e925997031478b",
          "sha256": "d8e3903bc91bc6736dfd267c81dd26e8436704d6f5dbc3f9034949b796b91679",
          "sha1": "d861aa256eca77f7651347aac9420f8e460f6344",
          "md5": "a82b32137bf8ae85779e350177e33ba5"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.6.0-profile.aar",
          "url": "flutter-1.6.0-profile.aar",
          "size": 350466,
          "sha512": "be695c79eed87b3fba43fd6a37cc84ea43449a0265fc976cf3ee446a90ac2fe5ba25f92b4944375f1c2a7184f56574369902bbbae16a4b0d36e925997031478b",
          "sha256": "d8e3903bc91bc6736dfd267c81dd26e8436704d6f5dbc3f9034949b796b91679",
          "sha1": "d861aa256eca77f7651347aac9420f8e460f6344",
          "md5": "a82b32137bf8ae85779e350177e33ba5"
        }
      ]
    }
  ]
}
