{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.7.0.aar",
          "url": "flutter_profile-1.7.0.aar",
          "size": 342052,
          "sha512": "cad65e4fc4465005bf7c572c10a9d11caa58b500212ed6da19a26c56194f0b48cdbc911df67fa8b4c5296b0147fca3b11d3619c78703ad29dec862bf3b8ff2ca",
          "sha256": "2523a66b4e18cdccda5ded279e66da2e948560344bce39eb05853f651ef86385",
          "sha1": "82178a672bc83f6f0b019396e2da9e2b2acb8d2e",
          "md5": "b140c02283fd3c4a7defcaa94aeac6f8"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.7.0.aar",
          "url": "flutter_profile-1.7.0.aar",
          "size": 342052,
          "sha512": "cad65e4fc4465005bf7c572c10a9d11caa58b500212ed6da19a26c56194f0b48cdbc911df67fa8b4c5296b0147fca3b11d3619c78703ad29dec862bf3b8ff2ca",
          "sha256": "2523a66b4e18cdccda5ded279e66da2e948560344bce39eb05853f651ef86385",
          "sha1": "82178a672bc83f6f0b019396e2da9e2b2acb8d2e",
          "md5": "b140c02283fd3c4a7defcaa94aeac6f8"
        }
      ]
    }
  ]
}
