{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.0.aar",
          "url": "flutter_profile-1.9.0.aar",
          "size": 10953763,
          "sha512": "cec58c091303b1f17fbf3d70f030ed39d84278d2fefb52e5dee2401ce84fd9827051137a580656fa816aaea989ebfca4632e0f132861cde64e041ad48a1f7f37",
          "sha256": "f601e828f3d9532a8c7f8f12179bdb8084c81c2e02249a1bb8b7c45534a867c9",
          "sha1": "49c83269b015edda37693a3934e4eccbefe30688",
          "md5": "bd1bd9247ee42b045970f8dee31aec40"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.0.aar",
          "url": "flutter_profile-1.9.0.aar",
          "size": 10953763,
          "sha512": "cec58c091303b1f17fbf3d70f030ed39d84278d2fefb52e5dee2401ce84fd9827051137a580656fa816aaea989ebfca4632e0f132861cde64e041ad48a1f7f37",
          "sha256": "f601e828f3d9532a8c7f8f12179bdb8084c81c2e02249a1bb8b7c45534a867c9",
          "sha1": "49c83269b015edda37693a3934e4eccbefe30688",
          "md5": "bd1bd9247ee42b045970f8dee31aec40"
        }
      ]
    }
  ]
}
