{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_release",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.0.aar",
          "url": "flutter_release-1.9.0.aar",
          "size": 7657739,
          "sha512": "356524b7f981f9ccb4eb17525eb5b59d8c9b3d81c6d4e1b5c20c80ece124f3f576574c703700abd5b58d568f03df634547ef9f8d8791e578c837603f81ab89d1",
          "sha256": "5365dbc5a36b222aa9312a851caf48193b0c39e74bce9fbd193dd987051d39c5",
          "sha1": "177db6ab08f629c232e72cc09508d873e29238cc",
          "md5": "db9b3d7fa7789eace2264b59725c00a3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.0.aar",
          "url": "flutter_release-1.9.0.aar",
          "size": 7657739,
          "sha512": "356524b7f981f9ccb4eb17525eb5b59d8c9b3d81c6d4e1b5c20c80ece124f3f576574c703700abd5b58d568f03df634547ef9f8d8791e578c837603f81ab89d1",
          "sha256": "5365dbc5a36b222aa9312a851caf48193b0c39e74bce9fbd193dd987051d39c5",
          "sha1": "177db6ab08f629c232e72cc09508d873e29238cc",
          "md5": "db9b3d7fa7789eace2264b59725c00a3"
        }
      ]
    }
  ]
}
