{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_release",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.0.aar",
          "url": "flutter_release-1.6.0.aar",
          "size": 6799606,
          "sha512": "6f2a6e28548e65a19b9cda51b483bb780f33bcf3ed8b940c7d3f2b9cc2858764ae6d7b2191a5a1dc6864dfd3044bba2032115b77bec637dc9141fe52eced1cfd",
          "sha256": "f0d46f8941eb1c093a7ba203bb5dc3fff1306a0ef39008a6628f32434d7efcf5",
          "sha1": "7816aa7466e2a9e8b06e3763a2c5d5b8a447b9ca",
          "md5": "e5253668f2960951441a9193f6330f1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.0.aar",
          "url": "flutter_release-1.6.0.aar",
          "size": 6799606,
          "sha512": "6f2a6e28548e65a19b9cda51b483bb780f33bcf3ed8b940c7d3f2b9cc2858764ae6d7b2191a5a1dc6864dfd3044bba2032115b77bec637dc9141fe52eced1cfd",
          "sha256": "f0d46f8941eb1c093a7ba203bb5dc3fff1306a0ef39008a6628f32434d7efcf5",
          "sha1": "7816aa7466e2a9e8b06e3763a2c5d5b8a447b9ca",
          "md5": "e5253668f2960951441a9193f6330f1a"
        }
      ]
    }
  ]
}
