{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_release",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.0.aar",
          "url": "flutter_release-1.6.0.aar",
          "size": 6798372,
          "sha512": "332b2d1a02e9c4270839e776b24712eb964aa3b38f8536f1865471f163561dbf26527729b0e0d0579b5f255b5913c8f2afadec669a4729c4df7b2697e5e2b622",
          "sha256": "eb6b5ea4e2278735a7f2fb94f757a35a08146cb6e6602df1496b4ac639b47403",
          "sha1": "b8553d77d62a74b900547398d5a18c6fb5f3a953",
          "md5": "081bf8045abaf1f1c4a10c507c74e969"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.6.0.aar",
          "url": "flutter_release-1.6.0.aar",
          "size": 6798372,
          "sha512": "332b2d1a02e9c4270839e776b24712eb964aa3b38f8536f1865471f163561dbf26527729b0e0d0579b5f255b5913c8f2afadec669a4729c4df7b2697e5e2b622",
          "sha256": "eb6b5ea4e2278735a7f2fb94f757a35a08146cb6e6602df1496b4ac639b47403",
          "sha1": "b8553d77d62a74b900547398d5a18c6fb5f3a953",
          "md5": "081bf8045abaf1f1c4a10c507c74e969"
        }
      ]
    }
  ]
}
