{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_profile",
    "version": "1.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.6.aar",
          "url": "flutter_profile-1.9.6.aar",
          "size": 11089506,
          "sha512": "daecfb3108acba99cc0529fe1b5b68de87fdf6ff0557bd908bf1bb6dee8b89b2fa9a6f1ec9e33a273142c4121edb2a35b8aaffe6c40b9ec16de3dbbd81741bf2",
          "sha256": "94956a9fc1a823b17aad29814ff84c65aea7c1156a9ba00b35a34cd0921e1ae0",
          "sha1": "89b84d2541e69e62c5232574556751f3a9ba2888",
          "md5": "22ab70ba24ba0ab04841b9cd99447580"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-c9b9d5780da342eb3f0f5e439a7db06f7d112575"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.9.6.aar",
          "url": "flutter_profile-1.9.6.aar",
          "size": 11089506,
          "sha512": "daecfb3108acba99cc0529fe1b5b68de87fdf6ff0557bd908bf1bb6dee8b89b2fa9a6f1ec9e33a273142c4121edb2a35b8aaffe6c40b9ec16de3dbbd81741bf2",
          "sha256": "94956a9fc1a823b17aad29814ff84c65aea7c1156a9ba00b35a34cd0921e1ae0",
          "sha1": "89b84d2541e69e62c5232574556751f3a9ba2888",
          "md5": "22ab70ba24ba0ab04841b9cd99447580"
        }
      ]
    }
  ]
}
