{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_release",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.2.aar",
          "url": "flutter_release-1.9.2.aar",
          "size": 7534438,
          "sha512": "321706176c9010705309faf05036071d21fa7005cc75ca8f220fe8965df0a051f82615d02ac41442d4629a450131c45663863da5f30b32371fd98d8f4bb74564",
          "sha256": "78290a9e3bfe4f1ae4f05cbed68d6610bbad4cf6228e5b11dfe12743078f468a",
          "sha1": "6effdf04a7de06383ef49ae031891c7ee6da8247",
          "md5": "ade100cb167c04450ec8d28fffe973b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-767d8c75e898091b925519803830fc2721658d07"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.9.2.aar",
          "url": "flutter_release-1.9.2.aar",
          "size": 7534438,
          "sha512": "321706176c9010705309faf05036071d21fa7005cc75ca8f220fe8965df0a051f82615d02ac41442d4629a450131c45663863da5f30b32371fd98d8f4bb74564",
          "sha256": "78290a9e3bfe4f1ae4f05cbed68d6610bbad4cf6228e5b11dfe12743078f468a",
          "sha1": "6effdf04a7de06383ef49ae031891c7ee6da8247",
          "md5": "ade100cb167c04450ec8d28fffe973b6"
        }
      ]
    }
  ]
}
