{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_release",
    "version": "1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.2.aar",
          "url": "flutter_release-1.8.2.aar",
          "size": 7638789,
          "sha512": "ac79d14460ec640ac422eb591f5be8a872f6e3881d62a102281187a8d3c46191dcb8c53de38d077ea4219fcda1a959e3dbbbc0a78256d50e38966151f2738534",
          "sha256": "26689b438146be2010c4be4a2403bf2f4bb3c275021f82dd6cb50132769f3d6e",
          "sha1": "afd6d94b5f93746a206b2479fd5305efe8bb80d9",
          "md5": "93b10351b476b49f651e8417fc02d81c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.8.2.aar",
          "url": "flutter_release-1.8.2.aar",
          "size": 7638789,
          "sha512": "ac79d14460ec640ac422eb591f5be8a872f6e3881d62a102281187a8d3c46191dcb8c53de38d077ea4219fcda1a959e3dbbbc0a78256d50e38966151f2738534",
          "sha256": "26689b438146be2010c4be4a2403bf2f4bb3c275021f82dd6cb50132769f3d6e",
          "sha1": "afd6d94b5f93746a206b2479fd5305efe8bb80d9",
          "md5": "93b10351b476b49f651e8417fc02d81c"
        }
      ]
    }
  ]
}
