{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_debug",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.6.0.aar",
          "url": "flutter_debug-1.6.0.aar",
          "size": 12171215,
          "sha512": "43276a2fa34c888cc39106429403f71249bcf689390cb393ddf8425a84a25b658ff60022757066bce7a11362a6615e7882bbf85360b593212d2069aa8db63347",
          "sha256": "7fc1b250196592f995b15909110f4e6aff047086eff1254aba9c04d84209f5ff",
          "sha1": "20a7771c256e6d8bcf1980dc4cbf97becb90ec2b",
          "md5": "f440253ac20d5779c8eca785356c4a83"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.6.0.aar",
          "url": "flutter_debug-1.6.0.aar",
          "size": 12171215,
          "sha512": "43276a2fa34c888cc39106429403f71249bcf689390cb393ddf8425a84a25b658ff60022757066bce7a11362a6615e7882bbf85360b593212d2069aa8db63347",
          "sha256": "7fc1b250196592f995b15909110f4e6aff047086eff1254aba9c04d84209f5ff",
          "sha1": "20a7771c256e6d8bcf1980dc4cbf97becb90ec2b",
          "md5": "f440253ac20d5779c8eca785356c4a83"
        }
      ]
    }
  ]
}
