{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gigya.gigyaNativeScreensetsEngine",
    "module": "flutter_debug",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.8.1.aar",
          "url": "flutter_debug-1.8.1.aar",
          "size": 13479978,
          "sha512": "ba417425909e4ade12b1ebe04fc660aad7f5755f575c425645a8271a07dec06cd684977b46a5de74da7e69e166ccaadb34088c786cd61a7a89301296a9632212",
          "sha256": "2722a689cc8c875115e4c2e492d25af6311a7274181fb7b37e21c629719edf89",
          "sha1": "da002e76d6ae7b85a04350700c975f3fb07357b1",
          "md5": "f4a92af20120398a976f7739922eb133"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.8.1.aar",
          "url": "flutter_debug-1.8.1.aar",
          "size": 13479978,
          "sha512": "ba417425909e4ade12b1ebe04fc660aad7f5755f575c425645a8271a07dec06cd684977b46a5de74da7e69e166ccaadb34088c786cd61a7a89301296a9632212",
          "sha256": "2722a689cc8c875115e4c2e492d25af6311a7274181fb7b37e21c629719edf89",
          "sha1": "da002e76d6ae7b85a04350700c975f3fb07357b1",
          "md5": "f4a92af20120398a976f7739922eb133"
        }
      ]
    }
  ]
}
